# Generated by Django 5.0.6 on 2024-07-08 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chatting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='Topics',
        ),
        migrations.AddField(
            model_name='topic',
            name='chatting',
            field=models.ManyToManyField(blank=True, related_name='topics', to='base.chatting'),
        ),
        migrations.AddField(
            model_name='user',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='topics', to='base.topic'),
        ),
    ]
