# Generated by Django 5.0.6 on 2024-07-08 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_chatting_remove_user_topics_topic_chatting_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='chatting',
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
                ('category', models.ManyToManyField(blank=True, related_name='categories', to='base.category')),
            ],
        ),
        migrations.DeleteModel(
            name='Chatting',
        ),
    ]
