# Generated by Django 5.0.6 on 2024-08-10 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meeting',
            options={'ordering': ['headline', 'created']},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='Meeting',
            new_name='meeting',
        ),
        migrations.RenameField(
            model_name='meeting',
            old_name='title',
            new_name='headline',
        ),
        migrations.AlterField(
            model_name='meeting',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
