# Generated by Django 5.0.6 on 2024-08-10 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_meeting_options_rename_meeting_comment_meeting_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='headline',
            field=models.TextField(max_length=100),
        ),
    ]
